version: "3.8"

services:
  # Frontend  - STAGING
  experience-front-staging:
    container_name: ${CONTAINER_NAME}
    build:
      context: ../..
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}:latest
    ports:
      - "4203:${PORT}"
    restart: always
    env_file:
      - .env.staging
    networks:
      -  network_experiencesig
    labels:
      - com.experienciasig.environment=staging

networks:
  network_experiencesig:
     external: true
