version: "3.9"

services:
  # Frontend GESCOMPH - Producci√≥n
  experience-front-prod:
    container_name: ${CONTAINER_NAME}
    build:
      context: ../..
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}:latest
    restart: always
    ports:
      - "4204:${PORT}"
    env_file:
      - .env.prod
    networks:
      - network_experiencesig
    labels:
      -  com.experienciasig.environment=prod

# Red externa compartida con backend
networks:
  network_experiencesig:
    external: true