version: "3.9"

services:
  # Frontend GESCOMPH - Desarrollo
  experience-front-develop:
    container_name: ${CONTAINER_NAME}
    build:
      context: ../..
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}:latest
    restart: always
    ports:
      - "4201:${PORT}"
    env_file:
      - .env.dev
    networks:
      - network_experiencesig
    labels:
      -  com.experienciasig.environment=develop

# Red externa compartida con backend
networks:
  network_experiencesig:
    external: true

