version: "3.8"

services:
  # üåê API principal - DEVELOP
  exp-api-develop:
    container_name: ${CONTAINER_NAME}

    image: ${IMAGE_NAME}:latest     # ‚¨ÖÔ∏è Imagen creada por Jenkins (ya NO usa build)

    restart: always

    ports:
      - "${PORT}:${PORT}"

    env_file:
      - .env.dev

    networks:
      - network_experiencesig

    labels:
      - com.experienciasig.environment=develop

networks:
  network_experiencesig:
    external: true

